### ISSUE TITLE
false positiv

### ISSUE THREAD

**Issue by seema84** [e-im/ClickableLinks#3]
Paper 1.20.1
ClickableLinks  1.1.5

![url](https://github.com/e-im/ClickableLinks/assets/2832339/53b4c2b8-af8c-4385-9dc3-a6eb51035afe)

normal text is recognised as a link

**Comment by e-im** [comment]
This plugin re-implements detection exactly as it was done prior to 1.19.1. It is not meant to be good, rather to retain what was there before.

I suppose exposing the URL regex may be a solution to this, but I really would prefer not to add a configuration file here.

You can edit the regex in the plugin (it is only a few lines and one class) and then compile with `mvn package` should you want different detection behaviour.

**Comment by seema84** [comment]
What exactly would have to be adapted for this?

**Comment by e-im** [comment]
It depends what you want. Detecting what is and isn't a URL isn't as easy as it seems.
The simplest solution to the issue you pointed out with `test.test` could be resolved by removing this `?` here:
![chrome_FJBwzYk8AX](https://github.com/e-im/ClickableLinks/assets/76139600/eb3f3751-1483-49e4-bb83-891b93d7241d)

which would make it only detect links that start with `http://` or `https://`.

See this stackoverflow answer (or just google "url detection regex") to learn more about other options https://stackoverflow.com/questions/1500260/detect-urls-in-text-with-javascript

**Comment by seema84** [comment]
Thank you very much, I will try it out <3

**Comment by e-im** [comment]
I thought about this some more and I really do not want to add a config for this plugin-- just to keep it as simple as possible in restoring previous (pre-1.19.1) behaviour.

I hope you were able to resolve the issue.

**Comment by seema84** [comment]
> I thought about this some more and I really do not want to add a config for this plugin-- just to keep it as simple as possible in restoring previous (pre-1.19.1) behaviour.
> 
> I hope you were able to resolve the issue.

Unfortunately not yet. But thanks again for the feedback.
